# Create release from each tag push, build binaries
# TODO: darwin support

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  releases-matrix:
    name: Release dynamically-linked binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y gcc libpcap-dev
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Build linux-amd64
        run: env GOOS=linux GOARCH=amd64 go build -o scannerofcerts ./cmd/scannerofcerts
      - name: Build windows-amd64
        run: env GOOS=windows GOARCH=amd64 go build -o scannerofcerts.exe ./cmd/scannerofcerts
      - name: Convert tag to release & attach binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            scannerofcerts
            scannerofcerts.exe
